series: GLM Math
title: Rotation Matrix Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This is a demonstration of using a rotation matrix to describe an orientation in 3D space.
language: C++
tags:
  - Math
extra_resources:
  - title: A book on mathematics for 3D graphics on Amazon
    link: "http://www.amazon.com/Primer-Graphics-Development-Wordware-Library/dp/1556229119"
connections:
  - series: GLM Math
    title: Transforms Tutorial
