title: Rotation Matrix Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This is a demonstration of using a rotation matrix to describe an orientation in 3D space.
language: C++
image:
  icon: https://cloud.githubusercontent.com/assets/10502938/13506660/28be0300-e14d-11e5-90e3-b194f14e52bd.PNG
  banner: https://cloud.githubusercontent.com/assets/10502938/13506660/28be0300-e14d-11e5-90e3-b194f14e52bd.PNG
tags:
  - C++
  - Math
extra_resources:
  - "http://www.amazon.com/Primer-Graphics-Development-Wordware-Library/dp/1556229119"
connections:
  - "transforms-tutorial"
